'use client';
import { useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
export interface Column<T> { key: string; header: string; render?: (row: T) => React.ReactNode; sortable?: boolean; sortValue?: (row: T) => string | number; className?: string; }
export function DataTable<T>({ columns, data, pageSize = 10, rowKey, onRowClick, emptyState, initialSort }: { columns: Column<T>[]; data: T[]; pageSize?: number; rowKey: (r: T) => string; onRowClick?: (r: T) => void; emptyState?: React.ReactNode; initialSort?: { key: string; direction: 'asc' | 'desc' } }) {
  const [sort, setSort] = useState<{ key: string; direction: 'asc' | 'desc' } | null>(initialSort ?? null);
  const [page, setPage] = useState(1);
  const sorted = useMemo(() => { if (!sort) return data; const col = columns.find((c) => c.key === sort.key); if (!col?.sortValue) return data; const dir = sort.direction === 'asc' ? 1 : -1; return [...data].sort((a, b) => { const av = col.sortValue!(a), bv = col.sortValue!(b); return av < bv ? -1 * dir : av > bv ? 1 * dir : 0; }); }, [data, sort, columns]);
  const totalPages = Math.max(1, Math.ceil(sorted.length / pageSize));
  const cp = Math.min(page, totalPages);
  const pageData = sorted.slice((cp - 1) * pageSize, cp * pageSize);
  function handleSort(key: string) { setSort((p) => p?.key === key ? { key, direction: p.direction === 'asc' ? 'desc' : 'asc' } : { key, direction: 'asc' }); }
  return <div className="space-y-3"><div className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b bg-muted/40"><tr>{columns.map((col) => <th key={col.key} className={cn('px-4 py-3 text-left font-semibold text-foreground', col.sortable && 'cursor-pointer select-none hover:bg-muted/70')} onClick={() => col.sortable && handleSort(col.key)}><span className="inline-flex items-center gap-1">{col.header}{col.sortable && sort?.key === col.key && (sort.direction === 'asc' ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />)}</span></th>)}</tr></thead><tbody className="divide-y">{pageData.length === 0 ? <tr><td colSpan={columns.length} className="px-4 py-12 text-center text-muted-foreground">{emptyState ?? 'Không có dữ liệu'}</td></tr> : pageData.map((row) => <tr key={rowKey(row)} className={cn('transition-colors hover:bg-muted/30', onRowClick && 'cursor-pointer')} onClick={() => onRowClick?.(row)}>{columns.map((col) => <td key={col.key} className={cn('px-4 py-3 text-foreground', col.className)}>{col.render ? col.render(row) : (row as Record<string, unknown>)[col.key] as React.ReactNode}</td>)}</tr>)}</tbody></table></div></div>{sorted.length > pageSize && <div className="flex flex-col items-center justify-between gap-3 sm:flex-row"><p className="text-sm text-muted-foreground">Hiển thị {(cp - 1) * pageSize + 1}–{Math.min(cp * pageSize, sorted.length)} / {sorted.length} bản ghi</p><div className="flex items-center gap-1"><Button variant="outline" size="icon" onClick={() => setPage(1)} disabled={cp === 1}><ChevronsLeft className="h-4 w-4" /></Button><Button variant="outline" size="icon" onClick={() => setPage((p) => p - 1)} disabled={cp === 1}><ChevronLeft className="h-4 w-4" /></Button><span className="px-3 text-sm font-medium">{cp} / {totalPages}</span><Button variant="outline" size="icon" onClick={() => setPage((p) => p + 1)} disabled={cp === totalPages}><ChevronRight className="h-4 w-4" /></Button><Button variant="outline" size="icon" onClick={() => setPage(totalPages)} disabled={cp === totalPages}><ChevronsRight className="h-4 w-4" /></Button></div></div>}</div>;
}
